### ISSUE TITLE
Why is plpgsql function parsing experimental?

### ISSUE THREAD

**Issue by rex-remind101** [pganalyze/libpg_query#146]
Documentation for plpgsql function parsing is said to be experimental, but when I tested it on a variety of functions it appears to work. Would you mind documenting what about it makes it experimental since I intend to use it in a production setting so I'd like to know the constraints ahead of time. Thank you.

https://github.com/pganalyze/libpg_query/tree/13-2.1.2#usage-parsing-a-plpgsql-function-experimental

**Comment by lfittl** [comment]
@rex-remind101 That's mostly historic - I would say at this point you can use it in a production setting.

The reason it was marked as experimental initially is because we don't use the PL/pgSQL parser in the pganalyze app (it was more added as a useful utility to the library) - but since we've had a number of contributions to it over the years, I would feel confident using it at this point.
