### ISSUE TITLE
sha256hash change for 10-1.0.4 tar.gz release

### ISSUE THREAD

**Issue by MasterOdin** [pganalyze/libpg_query#173]
Our installation of `pg_query@1.3.0` suddenly started failing to compile, and we traced the issue back to this repo where it seems like the `tar.gz` download of [the `10-1.0.4`](https://github.com/pganalyze/libpg_query/releases/tag/10-1.0.4) release has had its sha256sum changed. The zip file has not been alerted. No idea what could have caused this (and the release itself doesn't say its been edited), but this seems very concerning.

Reproduced the issue locally doing:

```
$ wget -q https://github.com/pganalyze/libpg_query/archive/refs/tags/10-1.0.4.zip -O libpg_query-10-1.0.4.zip
$ wget -q https://github.com/pganalyze/libpg_query/archive/refs/tags/10-1.0.4.zip -O libpg_query-10-1.0.4.tar.gz
$ shasum -a 256 libpg_query-10-1.0.4
2a3749d64d8359ae3cd41620415106e02ed77b705860ee32cb394e186ce5cbf6  libpg_query-10-1.0.4.tar.gz
91e5146fc3c17f9897f40af62a1b2fd45039f28ddfa3a563ad3aa1e371471b27  libpg_query-10-1.0.4.zip
```

**Comment by lfittl** [comment]
Thanks for the report!

This is caused by https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/ - no change on our end, but rather GitHub causing a lot of problems to various open-source projects today :)

Per https://news.ycombinator.com/item?id=34587306 this change is in the process of being reverted (because it caused so many issues) - so hopefully this should resolve on its own shortly.

In general, my recommendation would be to upgrade to a newer pg_query release ([2.0.0](https://github.com/pganalyze/pg_query/blob/main/CHANGELOG.md#200-----2021-03-18) or newer), since this problem stems from the way the older releases download libpg_query code on demand. Per GitHub's own comments we cannot rely on their shasums to be stable.

**Comment by MasterOdin** [comment]
Thanks for the response and the links, I had totally missed that GH had done that and was assuming something more malicious was going on.

This break also did get us to update to the newest pg_query in the interim :+1:

**Comment by lfittl** [comment]
@MasterOdin Great, happy to hear you had an excuse to update pg_query :)

And for future reference, feel free to ask about things like this anytime - it doesn't hurt to check.

You can also email security@pganalyze.com if there is anything more sensitive that is security-related (even if it affects the open-source repositories we maintain, such as pg_query, and you are not a customer of the pganalyze product) - though of course its fine to report here, especially if its a public fact like a checksum error.
