### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by deva666** [pganalyze/libpg_query#235]
Thanks for this awesome library. My C knowledge is basic so this may be a stupid question.
Is it possible to add build this library so it runs on Android (or how to build it with Android NDK toolchain) ? 
I tried to build the library in Docker Ubuntu container and target the ARM64 architecture but when loading it on Android getting ` dlopen failed: library "libc.so.6" not found` error (I assume Android does not have it, it is Linux only ?). 
Also tried to convert this to Cmake and use Android NDK on my Mac but got too many errors.

Am I wasting my time, is it even possible to make it run on Android?

**Comment by lfittl** [comment]
@deva666 Thanks for reaching out!

Theoretically that should be possible, since it appears that people have run Postgres on Android before, and this library ultimately can be as portable as Postgres itself is (since it shares the code, with some modifications).

I believe the issue you're running into is more related to how you're building the library (i.e. in an Ubuntu container which has glibc installed), and not necessarily specific to libpg_query. Unfortunately I'm not familiar with how to build libraries for Android, but I would suggest starting with a simple "hello world" type library in C, and understanding how to compile that correctly first, and then trying to make libpg_query work.

**Comment by deva666** [comment]
Thanks for the answer!
