### ISSUE TITLE
PLPGSQL - Using record fields

### ISSUE THREAD

**Issue by rafaelthca** [pganalyze/libpg_query#38]
Hi,

Can't attribute values to record fields:

```
CREATE FUNCTION test(str character varying) RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v3 RECORD;
  v4 integer;
BEGIN
  select 1 as c1, 2 as c2 into v3;
  v3.c1 := 4;
END;$$;
```
Error:
```
ERROR: "v3.c1" is not a known variable
CONTEXT: compilation of PL/pgSQL function "test" near line 7
LOCATION: cword_is_not_variable, pl_gram.y:2534
```

But postgresql accepts this syntax.

Great library by the way, keep up the good work.

Rafael.

**Comment by rafaelthca** [comment]
The same happens when declaring variables with ROWTYPE from existing table. It obviously throws error because the table does not exist in the parser context. Is there a way to overcome this?

```
DECLARE
      myrow my_table%ROWTYPE;
```
```
ERROR: "my_table" is not a known variable
```

**Comment by lfittl** [comment]
Hi @rafaelthca - thanks for reaching out about this!

You are indeed correct that this doesn't work - the PL/pgSQL parser is a bit of work in progress, since it doesn't setup variables and return values correctly (yet).

See https://github.com/lfittl/libpg_query/blob/10-latest/src/pg_query_parse_plpgsql.c#L80 which is inspired by https://github.com/postgres/postgres/blob/REL_10_STABLE/src/pl/plpgsql/src/pl_comp.c#L794

If you have time to work on this help would be very welcome :)

**Comment by lfittl** [comment]
Fixed in https://github.com/pganalyze/libpg_query/commit/e9e4ba9ffcbac02bce6656ecabd22c2b54eca1b2
