### ISSUE TITLE
Comment token for lexical analysis

### ISSUE THREAD

**Issue by dacappo** [pganalyze/libpg_query#43]
We are running lexical analysis on PostgreSQL queries and using the expose-scanner commit (66470f27e0bd756770d30a7d2bc068b468e82561) on top of your 10-latest branch. The only thing we are missing are tokens for comments:

``SELECT * FROM x /* foo */;``

currently results in tokens

```
  tokens: 5, size: 45
  [ 0, 6, 597, 4 ]
  [ 7, 8, 42, 0 ]
  [ 9, 13, 417, 4 ]
  [ 14, 15, 258, 0 ]
  [ 25, 26, 59, 0 ]
```
For our use case of lexical analysis we require a token for the comments.

We are aware that this is not required for the parser.  Anyway, any idea how we can get these tokens from the scanner that requires minor code changes? (e.g. [src/postgres/src_backend_parser_scan.c](https://github.com/lfittl/libpg_query/blob/10-latest/src/postgres/src_backend_parser_scan.c))

Thumbs up for the great work!

Best, Patrick

**Comment by lfittl** [comment]
@dacappo Thanks for reaching out!

Thats a very good question, I remember caring about comments when I made that prototype (since my use case was syntax highlighting), but I think the conclusion was that it'd require to patch the scanner to not ignore them (i.e. not treat them like whitespace, as the scanner does right now).

Definitely doable but I didn't get back to actually implement that since. Also any patch to the scanner would have to be as minimal as possible, to make rebasing onto new Postgres versions easy.

Is your use case also syntax highlighting, or are you specifically looking to only extract the comments from a query?

**Comment by dacappo** [comment]
We would like to use the PostgreSQL lexer to check queries for SQL injections based on the results of our dynamic code analysis engine. Without the comment tokens, we cannot precisely detect the injection of comments that may chop further parts of the query. So we actually need all tokens the scanner processes.

**Comment by lfittl** [comment]
@dacappo Its been a while, but this has actually made it into the 2.0 release:

https://github.com/pganalyze/libpg_query#usage-scanning-a-query-into-its-tokens-using-the-postgresql-scannerlexer

(thanks to a small patch to the scanner to support retaining this information)
