### ISSUE TITLE
Doubt about parameter placeholders

### ISSUE THREAD

**Issue by lelit** [pganalyze/libpg_query#45]
Hi,

by pure chance I fed a statement like `SELECT foo FROM bar WHERE id = ?` to my `pg_query` prettifier, and was surprised to see that `libpg_query` parsed it without a noise, emitting a `ParamRef` without the usual `number` slot.

Is this intentional or not? In other words, should I release the trivial tweak I made to `pg_query` to handle the case? :smiley:

**Comment by lfittl** [comment]
@lelit That is intentional, since one of the initial motivations for pg_query was to support parsing pg_stat_statements queries (as part of pganalyze), and those had ? as placeholders before Postgres 10.

You can see the patch that does that here: https://github.com/lfittl/libpg_query/blob/10-latest/patches/01_parse_replacement_char.patch

On the prettifier side, its up to you - I could see it being useful to support this case (i.e. ParamRef without a number gets output as `?`)

**Comment by lelit** [comment]
Thank you for the clarification!
