### ISSUE TITLE
Support configuring the parser w/ relevant server settings?

### ISSUE THREAD

**Issue by ethanresnick** [pganalyze/libpg_query#50]
My understanding is that some PG server options can change how parsing works (e.g., `allow_nulls` and `standard_conforming_strings`). Does libpg_query support configuring the parser with these settings, to match the server? Can/should it?

**Comment by lfittl** [comment]
@ethanresnick Today there is no mechanism to modify these settings, mostly since there are very limited use cases for setting them.

Do you have a reason to want to set them / what's the use case?

**Comment by ethanresnick** [comment]
> Do you have a reason to want to set them

No, I was mostly just curious; my thought was that a user of this library who did have those settings applied on their server would likely want to match them in libpq_query, as it seems like having a guarantee of consistent parsing between the server and wherever libpq_query is running could be an important security property, and part of the reason people would want to use this library

**Comment by jawj** [comment]
+1 for `standard_conforming_strings`. If you want to parse like pg, you need to be able to match pg's alternative parsing modes.

**Comment by lfittl** [comment]
From a quick look, it looks like supporting `standard_conforming_strings` (as well as `backslash_quote` and `escape_string_warning`) should be pretty straightforward, since we already have thread local variables that represent their state: https://github.com/pganalyze/libpg_query/blob/15-latest/src/postgres/include/parser/parser.h#L58

Note that `allow_nulls` isn't relevant to raw parsing in my understanding - its only applicable once the input data is parsed, and hence would not matter for pg_query's use case (which is to work with raw parse trees).

Since this is mainly about the API then (if you use the library in C, you could already set those variables before calling pg_query_parse), I'm curious how anyone interested in this is using pg_query today, i.e. from which wrapper/for which functions.

@ethanresnick @jawj Could you share a few notes which functions you are calling where you'd see a benefit from that? (e.g. are you using the Ruby wrapper library to call the parser function itself, or the fingerprint functions, etc)

**Comment by ethanresnick** [comment]
@lfittl It's been quite a while since I worked with this library, but, at the time I opened the issue, I was using [my own fork](https://github.com/ethanresnick/node-pg-query-native) of a then-current Javascript wrapper, and calling its `parseQuery`/`parseQuerySync` methods. I was not using query fingerprinting. I was also using PL/PGSQL parsing, in case these settings effect that.

**Comment by jawj** [comment]
I'm using it from Node — `import { parse } from 'pgsql-parser';` — to parse out separate SQL statements in a text block.

**Comment by jawj** [comment]
Thank you!
