### ISSUE TITLE
Questions on the new (upcoming?) v13 support

### ISSUE THREAD

**Issue by lelit** [pganalyze/libpg_query#82]
Hi Lukas, first of all, thanks for your effort to maintain this library!

I spent a few hours into understanding the "what's new" in the 13-latest-develop branch, with the short term goal of adapting my `pglast` wrapper.

The following changes have obviously a considerable impact:

1. the new _top level result_ (introduced by commit 53ae0937b076d0f847ecbd57d105c05bd556bdb3)
2. omission of attributes with value of zero, in particular for `enum`s (commit f36f9ab7ef109a2280bb4198aa9c7de68001ca8e)

For the first, while I can see the advantage of getting rid of the mostly useless `RawStmt` _container_, I wonder what's the added value of reporting the underlying PG `version` in the parse result: why cannot it be simply a constant `#define` exposed by the library as before?

The second is more worrysome: I'm quite sure that the PG devteam won't change enums definitions with a light heart, but IMHO introducing such _implicitness_ just to reduce the output size is not a good move; is there any other rationale behind this change?

**Comment by lelit** [comment]
I'm slowly trying to align my pglast project to the PG13 branch, and I found a difference in the JSON output that I'm not able to understand/fix.

Getting the JSON AST of the statement
```sql
ALTER DEFAULT PRIVILEGES FOR ROLE admin REVOKE execute ON FUNCTIONS FROM PUBLIC
```
I used to get the following JSON structure with previous versions of the library
```json
[
  {
    "RawStmt": {
      "stmt": {
        "AlterDefaultPrivilegesStmt": {
          "action": {
            "GrantStmt": {
              "behavior": 0,
              "grantees": [
                {
                  "RoleSpec": {
                    "location": 73,
                    "roletype": 3
                  }
                }
              ],
              "objtype": 7,
              "privileges": [
                {
                  "AccessPriv": {
                    "priv_name": "execute"
                  }
                }
              ],
              "targtype": 2
            }
          },
          ...
        }
      }
    }
  }
]
```

while with the 13-latest-develop branch I get this:
```json
[
  {
    "RawStmt": {
      "stmt": {
        "AlterDefaultPrivilegesStmt": {
          "action": {
            "grantees": [
              {
                "RoleSpec": {
                  "location": 73,
                  "roletype": "ROLESPEC_PUBLIC"
                }
              }
            ],
            "objtype": "OBJECT_FUNCTION",
            "privileges": [
              {
                "AccessPriv": {
                  "priv_name": "execute"
                }
              }
            ],
            "targtype": "ACL_TARGET_DEFAULTS"
          },
          ...
        }
      }
    }
  }
]
```
As you can see, the the `action` seems lacking the proper `GrantStmt` _node tag_ (I mean, the action's attributes wrapped within a "GrantStmt" dictionary) as before... is this intentional or an unexpected regression?

Also, will you _elect_ the new `protobuf` output as the recommended way or is the `JSON` way going to stay there indefinitely?

Thank you.

**Comment by lelit** [comment]
I found the code that makes the difference, but I could not figure out the logic used by the Ruby generator of the functions...

Manually applying the following change, I get the expected result:
```diff
diff --git a/src/pg_query_outfuncs_defs.c b/src/pg_query_outfuncs_defs.c
index 2cb4572..19f372a 100644
--- a/src/pg_query_outfuncs_defs.c
+++ b/src/pg_query_outfuncs_defs.c
@@ -2585,7 +2585,7 @@ static void
 _outAlterDefaultPrivilegesStmt(OUT_TYPE(AlterDefaultPrivilegesStmt, AlterDefaultPrivilegesStmt) out, const AlterDefaultPrivilegesStmt *node)
 {
   WRITE_LIST_FIELD(options, options, options);
-  WRITE_SPECIFIC_NODE_PTR_FIELD(GrantStmt, grant_stmt, action, action, action);
+  WRITE_NODE_PTR_FIELD(action, action, action);
 }
```

Thanks for any clarification.

**Comment by lfittl** [comment]
@lelit Thanks for your notes here, and the early testing of the branch.

First of all, an overall note on the new formats:

Generally the idea is that the JSON parse tree will continue to be supported for output, but that using the deparser (which is now fully functional within the C library) requires the Protobuf library.

I will also be updating all directly maintained libraries (i.e. Ruby, Go, possibly others in the future) to utilize the Protobuf-based approach (since it improves the usability and speed of passing things between C and the other language).

Specific replies:

> the new top level result (introduced by commit 53ae093)
>
> while I can see the advantage of getting rid of the mostly useless RawStmt container, I wonder what's the added value of reporting the underlying PG version in the parse result: why cannot it be simply a constant #define exposed by the library as before?

The motivation here comes from the deparser, which now accepts back a parse tree to turn it into a SQL statement again. Doing so across Postgres versions, or even Postgres minor releases, would be undefined, and possibly hit issues. Therefore the top-level object exists as a way to validate the version the parse tree was generated for.

In client libraries it may also have another benefit, as you could theoretically support different major Postgres versions in case you have any helpers that rely on the specific parse tree format.

> Omission of attributes with value of zero, in particular for enums (commit f36f9ab)
>
> ... I'm quite sure that the PG devteam won't change enums definitions with a light heart, but IMHO introducing such implicitness just to reduce the output size is not a good move; is there any other rationale behind this change?

The reason for omitting the zero value comes from the fact that the JSON format now matches the auto-generated JSON output format for Protobuf (intentionally, as it possibly allows for conversion between the formats in the future). But I think we can workaround this issue by ensuring the actual value is never the first field, rather having a generic "unspecified" value as the first enum value thats never used. I'll explore this.

> I'm slowly trying to align my pglast project to the PG13 branch, and I found a difference in the JSON output that I'm not able to understand/fix.

I'll review this, thanks for the testing and bug report.

(also please be aware that the branch is still a bit unstable, and I'll be squashing changes for at least the next week or so - after that it should become more stable, with a target release in 2-3 weeks, if all goes well)

**Comment by lelit** [comment]
Thanks a lot Lukas!

I'm really happy about the `JSON`-way staying around: while I can clearly see the benefits that Protobuf brings, I'm not so happy about the footprint of the official Python _bindings_ (`protoc` generates a 1.2Mb Python module from the 100Kb pg_query.proto), so I'm not sure it's worth the hassle.

On the version signature in the stream, yes, I understand the purpose (see #32 :wink:), but still I fail to foresee a benefit of having it in each response... unless someone is going to persist the response and act on it at a (much) later time, with a different version of libpg_query. Anyway, it was just a curiosity of mine :smile:

On the omission of the _zero-valued_ attribute, I'll stay tuned. I think that I can easily workaround the issue with a bit of heuristic. At a glance, I thought it could cause the kind of issues that required you to introduce `patches/05_limit_option_enum_value_default.patch`...

On the branch stability, I'm aware of it and I'm prepared to `pull --force` now and then on my side.

**Comment by lelit** [comment]
As there's a non-zero chance that the problems reported above are generated by mis-compilation of libpg_query source after `git pull --force` (as happened in #84), please suspend investigation on your part, I'll report back as soon as time permits.

**Comment by lfittl** [comment]
> On the omission of the _zero-valued_ attribute, I'll stay tuned. I think that I can easily workaround the issue with a bit of heuristic. At a glance, I thought it could cause the kind of issues that required you to introduce `patches/05_limit_option_enum_value_default.patch`...

This is fixed now via https://github.com/lfittl/libpg_query/commit/115570289eecbe5de511ab8ff3934d0baabf8ec6 - I think that should address the problem.

> As there's a non-zero chance that the problems reported above are generated by mis-compilation of libpg_query source after git pull --force (as happened in #84), please suspend investigation on your part, I'll report back as soon as time permits.

I think the problem with the `GrantStmt` being omitted is actually intentional - when a field has a defined value on the Postgres side (i.e. it's not a generic node field), the better way to represent this is to not have the additional layer of indirection through the `Node` type.

This is again a case where the Protobuf-based approach defines the output format a bit (since the message type is specific there for the field, which causes it to not emit the node tag), and the JSON format is made to match.

Unfortunately there is no way to support the old style format going forward in this case, so I think this is something where you'll have to adjust the library a bit.

**Comment by pyramation** [comment]
@lfittl thanks for all your effort on this great library! I thought figured this issue was also relevant for my questions. (Let me know if it should be it's own issue)

The enums seem to be the string representation instead of the (sometimes arbitrary) internal integers. Was that a decision to make code more portable across major versions? For PG 10, I had built systems to do the mapping to integers, but I suppose that's not necessary when we upgrade, however, I would wonder out of curiosity if we'd be able to access the native integers? 

Also, I noticed that the `RangeVar` is not an ast node for `IndexStmt`'s `relation` field, but rather the props are inlined. Is this intentional? Similarly I saw same for `TypeName` node missing from a `ColumnDef`'s `typeName` field. Although these are redundant in practice and I can see the simplicity to remove them, It seems to break some of the parsing flow to inline these nodes as parameters, but maybe this is just a breaking change from the underlying major version upgrade? Apologies if any these types of questions are redundant. 

### example

```sql
CREATE UNIQUE INDEX new_unique_idx ON new_example(a, b);
```

### PG 10

```json
[
  {
    "RawStmt": {
      "stmt": {
        "IndexStmt": {
          "idxname": "new_unique_idx",
          "relation": {
            "RangeVar": {
              "relname": "new_example",
              "inh": true,
              "relpersistence": "p",
              "location": 38
            }
          },
          "accessMethod": "btree",
          "indexParams": [
            {
              "IndexElem": {
                "name": "a",
                "ordering": 0,
                "nulls_ordering": 0
              }
            },
            {
              "IndexElem": {
                "name": "b",
                "ordering": 0,
                "nulls_ordering": 0
              }
            }
          ],
          "unique": true
        }
      },
      "stmt_len": 55
    }
  }
]
```

### PG 13

```json
{
  "query": {
    "version": 130002,
    "stmts": [
      {
        "stmt": {
          "IndexStmt": {
            "idxname": "new_unique_idx",
            "relation": {
              "relname": "new_example",
              "inh": true,
              "relpersistence": "p",
              "location": 41
            },
            "accessMethod": "btree",
            "indexParams": [
              {
                "IndexElem": {
                  "name": "a",
                  "ordering": "SORTBY_DEFAULT",
                  "nulls_ordering": "SORTBY_NULLS_DEFAULT"
                }
              },
              {
                "IndexElem": {
                  "name": "b",
                  "ordering": "SORTBY_DEFAULT",
                  "nulls_ordering": "SORTBY_NULLS_DEFAULT"
                }
              }
            ],
            "unique": true
          }
        },
        "stmt_len": 58
      }
    ]
  },
  "stderr": ""
}
```

**Comment by lfittl** [comment]
> @lfittl thanks for all your effort on this great library! I thought figured this issue was also relevant for my questions. (Let me know if it should be it's own issue)

Hi @pyramation - thanks for making the effort to look at the new version!

> The enums seem to be the string representation instead of the (sometimes arbitrary) internal integers. Was that a decision to make code more portable across major versions? For PG 10, I had built systems to do the mapping to integers, but I suppose that's not necessary when we upgrade, however, I would wonder out of curiosity if we'd be able to access the native integers?

Yep, the change is intentional, as the integer values were pretty hard to understand, and this aligns the JSON output with the new Protobuf format.

You can access the enum integer values via the enum_defs.json file: https://github.com/lfittl/libpg_query/blob/13-latest-develop/srcdata/enum_defs.json

> 
> Also, I noticed that the `RangeVar` is not an ast node for indexes, but rather the props are inlined. Is this intentional? It seems to break some of the parsing flow to inline parameters, but maybe this is just a breaking change from the underlying major version upgrade? Apologies if any these types of questions are redundant.

Yeah, you are not the first one to notice, and this is a bit of a problematic change from a compatibility perspective, but is what will be in the final release (sorry about the extra work based on this!).

The motivation here comes from mapping more closely how the C structs inside Postgres represent the parse tree, and ensuring both the new Protobuf format as well as the JSON format (which now also maps directly to the way Protobuf would be represented as JSON) match that.

For context, when Postgres itself uses a generic node type (e.g.  `IndexStmt.whereClause`) we map that to a generic `pg_query.Node`, which will output the parse node name in the JSON format.

When Postgres itself uses a specific type for a field (e.g. `IndexStmt.relation`, as you noted) we map that directly to the specific node type, skipping the intermediate `pg_query.Node`. This also means that the JSON format no longer outputs the name of the child node in this case, because it will always be the same type.

You can see this clearly here in the new Protobuf definition as well: https://github.com/lfittl/libpg_query/blob/13-latest-develop/protobuf/pg_query.proto#L1085

Changing the JSON format here to have better backwards compatibility would break an intentional guarantee this new release makes (that the JSON format is a 1:1 representation of how the Protobuf format would be mapped to JSON - which will be important for future work on the deparser/etc).

You could use the `struct_defs.json` file to get the types for each field, as a way to workaround this problem programmatically: https://github.com/lfittl/libpg_query/blob/13-latest-develop/srcdata/struct_defs.json#L4469

**Comment by pyramation** [comment]
Thanks for the quick response! This all makes sense and I think long term will be better and more portable. 

And also thanks for all the relevant links, I'll be using these when I rebuild the node deparser. Much appreciated @lfittl :)

**Comment by lelit** [comment]
Thank you Lukas!

**Comment by lfittl** [comment]
@lelit @pyramation The Postgres 13 release is officially out now - full blog post here: https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser - I mentioned both of you by name as well, since you've been very helpful in taking an early look, as well as maintaining the Python/Node.js bindings :)

I'll close this issue here for now - but feel free to open new ones or ask here in case there are follow-up questions.
